### ISSUE TITLE
the bug of natrender

### ISSUE THREAD

**Issue by darcyq** [natmlx/NatCorder#1]
06-20 19:44:50.867 E/AndroidRuntime(15332): FATAL EXCEPTION: NatRender GLReadback
06-20 19:44:50.867 E/AndroidRuntime(15332): Process: com.wmyzf.an.global, PID: 15332
06-20 19:44:50.867 E/AndroidRuntime(15332): java.lang.RuntimeException: lock buffer failed for format 0x1
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.media.ImageReader$SurfaceImage.nativeCreatePlanes(Native Method)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:890)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at api.natsuite.natrender.GLReadback$1.onImageAvailable(GLReadback.java:120)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.os.Handler.dispatchMessage(Handler.java:108)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.os.Looper.loop(Looper.java:166)
06-20 19:44:50.867 E/AndroidRuntime(15332): 	at android.os.HandlerThread.run(HandlerThread.java:65)

Crash in Android 8.0.0+

**Comment by olokobayusuf** [comment]
NatRender and NatCorder Performance Extensions have been deprecated. The `GLESReadback` class [has been reimplemented in NatCorder 1.8.4](https://github.com/natmlx/NatCorder/releases/tag/1.8.4) from scratch. [Upgrade to NatCorder 1.8.4](https://github.com/natmlx/NatCorder#installing-natcorder).

**Comment by darcyq** [comment]
您好，您的邮件我已收到，谢谢！                                           刘金全
